version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
